#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

set -e; set -o pipefail; source ${DIR}/kerndev-shared.sh

# Since we specify an argument (the switch), we can't just pass $@.
source ${DIR}/kerndev-check-all --max-line-length=1000 ${@:-*.[ch]}
